@url = http://localhost:3000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjI1YzlkMTYwLTY4YTItNDFlOC1hMjQzLTg1YjM3NmIxOWI0ZCIsImlhdCI6MTc4NzA0Mzg1MCwiZXhwIjoxNzg3NjQ4NjUwfQ.4HqmoM9l7pDoqc5eKiZGXaocO8cAWKlAh_OSwvBKmiQ 


###
POST {{url}}/link HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "longUrl": "https://chatgpt.com/c/6a841e33-c3c0-83ee-80ec-08840ab9f99e"
}

###
PATCH {{url}}/link/f524f7a8-868c-4b68-9cfb-c6fee223a4fc HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "shortUrl": "myshop"
}

###
POST {{url}}/link/f524f7a8-868c-4b68-9cfb-c6fee223a4fc/qrcode HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "customization": {
        "color": "#000000",
        "backgroundColor": "#ffffff",
        "logo": "https://example.com/logo.png"
    } 
}








###
POST {{url}}/auth/signup HTTP/1.1
Content-Type: application/json

{
    "email": "t1@gmail.com",
    "password": "123123123",
    "confirmPassword": "123123123"
}

###
POST {{url}}/auth/signin HTTP/1.1
Content-Type: application/json

{
    "email": "t@gmail.com",
    "password": "123123123"
}

###
POST {{url}}/auth/protected HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}
# withCredentials: true

{
    "email": "t@gmail.com",
    "password": "123123123"
}























###
POST {{url}}/expense HTTP/1.1
Content-Type: application/json
withCredentials: true

{
   "title": "Bike maintance",
   "message": "regular maintance",
   "category": "Annual",
   "amount": 150
}

###
GET {{url}}/expense?startTime=2026-06-01&endTime=2026-06-30T13:55:38.508Z HTTP/1.1
Content-Type: application/json
withCredentials: true

# {
#    "title": "Car maintance",
#    "message": "regular maintance",
#    "category": "Annual",
#    "amount": 1500
# }


###
PATCH {{url}}/expense/e6b1da7c-63b1-468d-a138-6058ce7aa92c HTTP/1.1
Content-Type: application/json
withCredentials: true

{
   "title": "Airplane maintance",
   "message": "regular maintance",
   "category": "Annual",
   "amount": 14000
}

###
DELETE {{url}}/expense/4d19e6c3-a634-411c-8743-96135f8fac7a HTTP/1.1
Content-Type: application/json
withCredentials: true