@url = http://localhost:3000/api/v1
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImE0OTVjZmQ5LTViNWMtNDhlMC1hMTIzLWM3NjQ2MTdhZjkxMiIsImlhdCI6MTc4OTkyMDkyOSwiZXhwIjoxNzkwNTI1NzI5fQ.aAtTE5ziWzpAflqwaXmEoaXPy9zoYshO4ERGZ7M-oOw 

###
GET {{url}}/links/check/coo HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}


###
POST {{url}}/link HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "longUrl": "https://chatgpt.com/c/6a841e33-c3c0-83ee-80ec-08840ab9f99e"
}

###
PATCH {{url}}/link/f524f7a8-868c-4b68-9cfb-c6fee223a4fc HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "shortUrl": "myshop"
}

###
POST {{url}}/link/f524f7a8-868c-4b68-9cfb-c6fee223a4fc/qrcode HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "customization": {
        "color": "#000000",
        "backgroundColor": "#ffffff",
        "logo": "https://example.com/logo.png"
    } 
}

###
GET {{url}}/analytics/f2c99af1-8303-4856-9e99-830c62f87763?granularity=day HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

###
GET {{url}}/analytics/<LINK_ID>?granularity=<GRANULARITY>&from=<FROM>&to=<TO> HTTP/1.1
Content-Type: application/json
Authorization: Bearer {{token}}

